source 'http://rubygems.org'
source 'http://gemcutter.org'
gem 'sinatra-tests'
gem 'sinatra'
gem 'sinatra-google-auth', :git => 'git@github.com:HungryAcademyTeam4/sinatra-google-auth.git'
# gem 'sinatra-google-auth', path: '/Users/jacquelinechenault/Dropbox/Hungry Academy/Projects/chatlocker/sinatra-google-auth'
gem 'rake'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem "rack-test", require: 'rack/test'
gem 'capybara'

