source 'http://rubygems.org'
gem 'sinatra'
gem 'sinatra-google-auth', :git => 'git@github.com:HungryAcademyTeam4/sinatra-google-auth.git'
# gem 'sinatra-google-auth', path: '/Users/jacquelinechenault/Dropbox/Hungry Academy/Projects/chatlocker/sinatra-google-auth'  
gem 'rake'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3'
